(()=>{"use strict";
const $=s=>document.querySelector(s),form=$("#search-form"),input=$("#search-input"),grid=$("#materials-grid"),count=$("#result-count"),empty=$("#empty-state"),emptyTitle=$("#empty-title"),emptyText=$("#empty-description"),active=$("#active-query"),subject=$("#subject-filter"),grade=$("#grade-filter"),unit=$("#unit-filter"),state={query:"",subject:"",grade:"",unit:"",items:[]};
const norm=v=>String(v??"").toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ı/g,"i").replace(/[^a-z0-9]+/g," ").trim();
const codeOf=m=>String(m.outcomeCode||"").trim()||((String(m.outcome||"").match(/^([A-ZÇĞİÖŞÜ]+(?:\.[A-ZÇĞİÖŞÜ0-9]+)+\.?)/)||[])[1]||"");
const topicOf=m=>String(m.outcomeTopic||m.topic||m.outcome||"").replace(codeOf(m),"").replace(/^[\s:–—.-]+/,"").trim();
const searchText=m=>[m.title,m.description,m.subject,m.grade,m.unit,m.topic,m.outcome,m.outcomeCode,topicOf(m),codeOf(m),m.keywords,m.fileName].flat().filter(Boolean).join(" ");
const unique=a=>[...new Set(a.filter(Boolean).map(String))].sort((a,b)=>a.localeCompare(b,"tr"));
function fill(el,label,opts){const old=el.value;el.replaceChildren(new Option(label,""));opts.forEach(v=>el.add(new Option(v,v)));if(opts.includes(old))el.value=old}
function filters(){
 const byGrade=state.items.filter(m=>!state.grade||m.grade===state.grade);
 const bySubject=byGrade.filter(m=>!state.subject||m.subject===state.subject);
 const byUnit=bySubject.filter(m=>!state.unit||m.unit===state.unit);
 fill(grade,"Tüm sınıflar",unique(state.items.map(m=>m.grade)));
 fill(subject,"Tüm dersler",unique(byGrade.map(m=>m.subject)));
 fill(unit,"Tüm üniteler",unique(bySubject.map(m=>m.unit)));
}
function chip(t){const e=document.createElement("span");e.className="meta-chip";e.textContent=t;return e}
function appendHighlighted(el,text,terms){const raw=String(text??"");if(!raw){el.textContent="";return}const chars=[...raw],map=[];const normalized=chars.map((ch,i)=>{const n=ch.toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ı/g,"i");return [...n].map(c=>{map.push(i);return /[a-z0-9]/.test(c)?c:" "}).join("")}).join("");const ranges=[];for(const term of terms){let at=0;while(term&&(at=normalized.indexOf(term,at))!==-1){const start=map[at],end=map[Math.min(map.length-1,at+term.length-1)]+1;if(start!==undefined&&end>start)ranges.push([start,end]);at+=Math.max(term.length,1)}}ranges.sort((a,b)=>a[0]-b[0]||b[1]-a[1]);const merged=[];for(const r of ranges){const last=merged[merged.length-1];if(last&&r[0]<=last[1])last[1]=Math.max(last[1],r[1]);else merged.push([...r])}let cursor=0;for(const [start,end] of merged){if(start<cursor)continue;el.append(document.createTextNode(chars.slice(cursor,start).join("")));const mark=document.createElement("mark");mark.textContent=chars.slice(start,end).join("");el.append(mark);cursor=end}el.append(document.createTextNode(chars.slice(cursor).join("")))}
function card(m,terms){const a=document.createElement("article");a.className="material-card";const top=document.createElement("div");top.className="card-topline";const badge=document.createElement("span");badge.className="type-label";badge.textContent="Ders materyali";top.append(badge);if(m.fileSize){const size=document.createElement("span");size.className="file-size";size.textContent=m.fileSize;top.append(size)}const h=document.createElement("h3");appendHighlighted(h,m.title||"İsimsiz materyal",terms);a.append(top,h);if(m.description){const d=document.createElement("p");d.className="card-description";appendHighlighted(d,m.description,terms);a.append(d)}const meta=document.createElement("div");meta.className="card-meta";[m.grade,m.subject,m.unit].filter(Boolean).forEach(v=>{const c=chip(v);appendHighlighted(c,v,terms);meta.append(c)});const code=codeOf(m),topic=topicOf(m);if(code){const c=chip("Kazanım kodu: "+code);appendHighlighted(c,"Kazanım kodu: "+code,terms);meta.append(c)}if(topic){const c=chip("Konu: "+topic);appendHighlighted(c,"Konu: "+topic,terms);meta.append(c)}a.append(meta);const link=document.createElement("a");link.className="card-download";link.href=m.url;link.setAttribute("download","");link.setAttribute("aria-label",(m.title||"Materyal")+" dosyasını indir");const icon=document.createElementNS("http://www.w3.org/2000/svg","svg");icon.setAttribute("viewBox","0 0 24 24");icon.setAttribute("fill","none");icon.setAttribute("aria-hidden","true");const path=document.createElementNS("http://www.w3.org/2000/svg","path");path.setAttribute("d","M12 3v12m0 0 4.5-4.5M12 15l-4.5-4.5M4 17v3h16v-3");path.setAttribute("stroke","currentColor");path.setAttribute("stroke-width","1.8");path.setAttribute("stroke-linecap","round");path.setAttribute("stroke-linejoin","round");icon.append(path);const label=document.createElement("span");label.textContent="Materyali indir";link.append(icon,label);a.append(link);return a}
function render(){const terms=norm(state.query).split(/\s+/).filter(Boolean);const found=state.items.filter(m=>terms.every(t=>norm(searchText(m)).includes(t))&&(!state.subject||m.subject===state.subject)&&(!state.grade||m.grade===state.grade)&&(!state.unit||m.unit===state.unit));grid.replaceChildren(...found.map(m=>card(m,terms)));grid.setAttribute("aria-busy","false");count.textContent=found.length+" materyal";empty.hidden=found.length>0;grid.hidden=!found.length;if(!state.items.length){emptyTitle.textContent="Henüz materyal eklenmedi";emptyText.textContent="Materyaller eklendikçe burada listelenecek."}else if(state.query||state.subject||state.grade||state.unit){emptyTitle.textContent="Eşleşen materyal bulunamadı";emptyText.textContent="Arama ifadesini sadeleştir veya filtreleri temizleyerek yeniden dene"}else{emptyTitle.textContent="Materyaller henüz hazır değil";emptyText.textContent="Yeni materyaller eklendiğinde bu alanda görünecek"}const parts=[state.query?'Arama: “'+state.query+'”':"",state.grade,state.subject,state.unit].filter(Boolean);active.hidden=!parts.length;active.textContent=parts.join(" · ")}
function resetFilters(){state.subject=state.grade=state.unit="";subject.value=grade.value=unit.value="";filters()}
function query(q){state.query=q.trim();input.value=state.query;render()}
form.addEventListener("submit",e=>{e.preventDefault();query(input.value);$("#materyaller").scrollIntoView({behavior:"smooth",block:"start"})});
$("#back-top").addEventListener("click",()=>window.scrollTo({top:0,behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"}));input.addEventListener("input",()=>{state.query=input.value;render()});
grade.addEventListener("change",()=>{state.grade=grade.value;state.subject=state.unit="";subject.value=unit.value="";filters();render()});
subject.addEventListener("change",()=>{state.subject=subject.value;state.unit="";unit.value="";filters();render()});
unit.addEventListener("change",()=>{state.unit=unit.value;filters();render()});
$("#clear-filters").addEventListener("click",()=>{resetFilters();render()});
$("#reset-search").addEventListener("click",()=>{state.query="";input.value="";resetFilters();render();input.focus()});
document.querySelectorAll("[data-query]").forEach(b=>b.addEventListener("click",()=>{query(b.dataset.query);$("#materyaller").scrollIntoView({behavior:"smooth",block:"start"});input.focus({preventScroll:true})}));
fetch("data/materials.json").then(r=>{if(!r.ok)throw Error("catalogue");return r.json()}).then(data=>{state.items=Array.isArray(data)?data.filter(m=>m&&typeof m.title==="string"&&typeof m.url==="string"&&/^(https?:|\.\.?\/|\/)/.test(m.url)):[];filters();render()}).catch(()=>{state.items=[];filters();render();emptyTitle.textContent="Materyaller yüklenemedi";emptyText.textContent="Bağlantını kontrol edip sayfayı yenile.";count.textContent="Liste alınamadı"});
})();